baseURL: https://main--peppy-cajeta-252969.netlify.app
languageCode: en-us
title: Midlife Journey Blog
theme: PaperMod

params:
  comments: true
  homeInfoParams:
    Title: 'Hello Stranger'
    Content: "Welcome to my blog. Here you'll find a lot of cool information about me"
  socialIcons:
    - name: facebook
      url: 'www.facebook.com'
    - name: github
      url: 'www.github.com'
    - name: twitter
      url: 'www.twitter.com'

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

services:
  disqus:
    shortname: midlife-journey-blog